spring:
  datasource:
    url: jdbc:p6spy:postgresql://localhost:5435/wvs
    username: postgres
    password: password
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true

server:
  port: 8787

ipGeolocation:
  url: https://api.ipgeolocation.io/ipgeo
  apiKey: bdc584375cf94dda934bf6cea7879c30
