spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/wvs
    username: postgres
    password: password

server:
  port: 8787

ipGeolocation:
  url: https://api.ipgeolocation.io/ipgeo
  apiKey: bdc584375cf94dda934bf6cea7879c30
